language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"     
  - "dev"
  - "blead"
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
  allow_failures:
    - perl: blead
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto